"""修改说明11

Revision ID: 0a220b1ed311
Revises: b60b676c2ca2
Create Date: 2020-08-03 10:45:58.461305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a220b1ed311'
down_revision = 'b60b676c2ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('posts_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('posts_id')
    )
    op.add_column('admin_user', sa.Column('active', sa.BOOLEAN(), server_default='0', nullable=True, comment='0=未激活 1=激活'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'active')
    op.drop_table('posts')
    # ### end Alembic commands ###
