"""提交说明

Revision ID: 5a5ca20e7fd1
Revises: 
Create Date: 2020-07-29 11:02:43.693297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5ca20e7fd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色Id'),
    sa.Column('role_name', sa.String(length=64), nullable=True, comment='角色名字'),
    sa.Column('permission_id', sa.BIGINT(), nullable=True, comment='权限ID'),
    sa.Column('re_mark', sa.String(length=128), nullable=True, comment='备注信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ct', sa.String(length=19), nullable=True),
    sa.Column('ut', sa.String(length=19), nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'id'),
    comment='管理员角色'
    )
    op.create_index(op.f('ix_admin_role_role_id'), 'admin_role', ['role_id'], unique=False)
    op.create_table('admin_user',
    sa.Column('user_id', sa.String(length=32), nullable=True, comment='用户id'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=16), nullable=True, comment='手机号'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='管理员昵称'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('is_active', sa.BOOLEAN(), server_default='0', nullable=True, comment='0=未激活 1=激活'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色表'),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default='0', nullable=True, comment='0=普通用户 1=管理员'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ct', sa.String(length=19), nullable=True),
    sa.Column('ut', sa.String(length=19), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='管理员表'
    )
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_index(op.f('ix_admin_user_phone'), 'admin_user', ['phone'], unique=True)
    op.create_table('user',
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ct', sa.String(length=19), nullable=True),
    sa.Column('ut', sa.String(length=19), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_admin_user_phone'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_table('admin_user')
    op.drop_index(op.f('ix_admin_role_role_id'), table_name='admin_role')
    op.drop_table('admin_role')
    # ### end Alembic commands ###
