"""修改说明11

Revision ID: 5fa961ca272c
Revises: 0a220b1ed311
Create Date: 2020-08-03 10:51:07.926181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fa961ca272c'
down_revision = '0a220b1ed311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('id', sa.String(length=100), nullable=False))
    op.drop_column('posts', 'posts_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posts_id', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('posts', 'id')
    # ### end Alembic commands ###
