"""posts

Revision ID: b60b676c2ca2
Revises: c0488b41feec
Create Date: 2020-08-03 10:40:54.450919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60b676c2ca2'
down_revision = 'c0488b41feec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
