"""posts

Revision ID: c0488b41feec
Revises: b366a8494641
Create Date: 2020-08-03 10:20:51.273871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0488b41feec'
down_revision = 'b366a8494641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
